#ifndef FERTH_CONSTANTS
#define FERTH_CONSTANTS


#define FERTH_MAX_SCOPE_NESTLEMENT 128

#define FERTH_ERROR_DETAILS_COLOR 96
#define FERTH_ERROR_DETAIL_BOLD_COLOR 94
#define FERTH_ERROR_COLOR 31

#define ANSII_ESCAPE_RESET "\033[m"
#define FERTH_ERROR_DETAILS_ANSII_ESCAPE "\033[1;96m"
#define FERTH_ERROR_DETAIL_BOLD_ANSII_ESCAPE "\033[1;31m]"
#define FERTH_ERROR_ANSII_ESCAPE "\033[1;31m]"

#endif